name: ExtendedBlocks
version: 2.0.0-1
api: 4.0.0
description: Adds support to implements blocks with ID's 255+
author: Javier Leon9966
main: JavierLeon9966\ExtendedBlocks\Main
extensions:
  Core: '>=7.4'
